### ISSUE TITLE
Clear input box on submit

### ISSUE THREAD

**Issue by laurieek** [mgwdev81/notice-board#5]
Currently, when submitting the form, the input box is not cleared.

**Comment by mgwdev81** [comment]
This issue is no longer occurring. I think the form submit action was causing the entire page to refresh which resulted in a cleared text area. When I added `e.preventDefault();` to stop the page refresh when submitting a new notice, the text area was no longer being cleared. I added `this.setState({ value: "" });` to clear the text area after posting the new notice. I should improve this by only clearing the text area if the notice was indeed successfully added to the database (and also provide feedback to the user when the adding of a new notice is unsuccessful).
